# Generated by Django 2.0.1 on 2018-01-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questiontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerMCQ',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
                ('option', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
                ('answer', models.TextField(max_length=1200)),
            ],
            bases=('quiz.question',),
        ),
        migrations.RemoveField(
            model_name='questiontext',
            name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=1200),
        ),
        migrations.DeleteModel(
            name='QuestionText',
        ),
    ]
