# Generated by Django 2.0.1 on 2018-03-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180119_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answermcq',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='answertext',
            name='question_ptr',
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='AnswerMCQ',
        ),
        migrations.DeleteModel(
            name='AnswerText',
        ),
    ]
